### ISSUE TITLE
ERROR: Cannot bind socket to port

### ISSUE THREAD

**Issue by PayteR** [ondra-novak/mmbot#16]
Zdravim, robota som skompiloval ale led sa ho snazim spustit, tak mi napise tuto chybu

```
payter@mmbot:/media/sf_mmbot/mmbot$ bin/mmbot -p 10000 start
payter@mmbot:/media/sf_mmbot/mmbot$ ERROR: Cannot bind socket to port:/media/sf_mmbot/mmbot/run/inst.pid:666 - Operation not permitted
```
A robi pri akomkolvek porte, robi to aj pri root spusteni, ako to vyriesit? dik

**Comment by ondra-novak** [comment]
Zdravim. Chyba se tyka toho vypsaneho souboru, robot se jej snaží vytvořit ale nemůže protože nemá na to právo. Zkontroloval bych vlastníka adresáře run. Je možný ze patří rootovi. Možná ze celý strom patří rootovi, protože jste to rozbaloval nebo kompiloval pod rootem. Kdyztak jako root stačí použít prikaz `chown -R uziv:uziv .` a změnit práva celého projektu na požadovaného vlastníka. `ls -la` vypíše adresář i s vlastníky

**Comment by PayteR** [comment]
Diky za odpoved, nenapisal som dolezitu vec a to, ze som vo Virtualboxe a priecinok s kodom mam sharovany z Windowsu a to sa ukazuje ako problem prave, lebo nemozem menit opravenia suborov. Chcel som to takto mat, aby som mohol vo Windowse upravovat kod vo Visual Studiu, takze to budem musiet vymysliet inak. 

Este mam OT otazku: Za projektom vidiet kopu prace, klobuk dolu, je nejaky specificky dovod, preco je to nakodene v C++?

**Comment by ondra-novak** [comment]
V configu lze soubor přesměrovat třeba do /tmp a pak by to mělo jít.

V c++ je napsaný proto, že v něm perfektně umím programovat. JIný důvod to nemá.

**Comment by PayteR** [comment]
No skusim este to, ale uz teraz vidim, ako sa tam vyskytne dalsi problem, lebo uz po tento krok som ich mal viacero :D 

Skoda ze ja ho perfektne neovladam :D Nejaky tip ako sa do neho dostat co najrychlejsie? Okrem par hodin na vyske som s nim nerobil, inak najblizsie ovladam C#, problemy pri C++ mi hlavne robi pochopenie spravy pamate a tie operatory, ktorym vobec nechapem.

**Comment by ondra-novak** [comment]
C++ se poslední dobou hodně změnilo. Třeba v robotovi se zpráva paměti řeší na minimálně místech a to většinou v knihovnách za účelem performance. Zato hodně používám nové třeba lambda funkce a hromadu nových featur, proto je min verze 17
