### ISSUE TITLE
Internal Server Error - Resolved

### ISSUE THREAD

**Issue by McxCZE** [ondra-novak/mmbot#18]
Zdravím, předem supr věc že někdo z české komunity vyvíjí obdobnou věc, zajímavý bot hlavně i s popsanými taktikami. 

Nyní k problémku který se mi zde jeví. 

API klíče nahrané, Settings aplikované, bot vypnut/zapnut. Nastavení drží. V Access Control vidím zelenou fajfku u Binance. 

![image](https://user-images.githubusercontent.com/2656561/114007903-069b7380-9862-11eb-9c0e-29fd85484155.png)

**Comment by McxCZE** [comment]
![image](https://user-images.githubusercontent.com/2656561/114060480-b4744580-9895-11eb-8fe6-d6b650b3064d.png)

Skoro jak kdybych měl špatně API klíč, ale ten jsem si ještě vygeneroval a připravil. Nevím. Je možné že změnily API na své straně ?

**Comment by McxCZE** [comment]
Poloniex šlape :). Tak to bude asi blbina u toho Binance.

**Comment by ondra-novak** [comment]
V tom logu vidím chybu přímo z Binance, která si stěžuje, že podpis není validní. Což asi není problém nějakých změn, opravdu bych to tipoval na špatný klíč.

Provedl ale následující kontrolu. Jestli náhodou klíč (obé části) nejsou skopírované s mezerou na začátku nebo na konci, nebo se znakem konce řádky. Pokusím se tam udělat nějakou kontrolu na tyhle znaky, ale jsem si téměř jist, že teď ta kontrola tam není

**Comment by McxCZE** [comment]
Dobrý den, díky moc za inf. To je to moje "klikání"... Překopíroval jsem si klíč z Binance do Notepad++ a mrška přidává mezírku. Je to moje blbost, omlouvám se. Díky i tak mockrát za pomoc.

**Comment by McxCZE** [comment]
The Issue is resolved. Thank you very much.
