### ISSUE TITLE
calc_range nefunguje

### ISSUE THREAD

**Issue by medy75** [ondra-novak/mmbot#2]
Pokusil jsem se pustit (podle dokumentace) funkci calc_range, ale nevypisuje požadovaný výsledek. Pokusil jsem se i změnit velikost external_assets (původně jsem měl nastaveno na 0.0) zpět na defaultních 0.5, ale se stejným výsledkem.

```
$ bin/mmbot calc_range
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```

**Comment by ondra-novak** [comment]
Zdravím

mělo by to být fixnutý:
https://github.com/ondra-novak/mmbot/commit/3b7e80d3c5125d9045cd700c366503ffe5a7464c
