### ISSUE TITLE
SimpleLeveraged - Bug

### ISSUE THREAD

**Issue by McxCZE** [ondra-novak/mmbot#22]
SimpleLeveraged otevřel short pozici, pravděpodobně přestřelil uzavírací order na otevřenou pozici.

Zde nastavení.
![image](https://user-images.githubusercontent.com/2656561/127016142-13658220-2456-4509-8064-bbc5b0f7c664.png)

Zde provedené ordery.
![image](https://user-images.githubusercontent.com/2656561/127016212-ed74d8e0-adfd-42d5-8994-6f617bf2d5c2.png)

Manuálně jsem uzavřel -6 ADA na burze po zhruba dni kdy s tím nehýbal a sell ordery neměl žádné (respektive měl na 0 ADA) v pozici -6 ADA.

**Comment by McxCZE** [comment]
Vyřešeno nastavením "order size" na 100%, pravděpodobně chyba při výpočtu uzavření pozice, v momentě kdy se order size zvýší o více jak 100%. Vše funguje jak má.

**Comment by ondra-novak** [comment]
Order Size jiny 100% dělá dost divné věci. Přemýšlím, jestli ho tam nechávat. Je to option, které nemá strategie v moci, takže nemůže vědět, že při zavírání pozice dojde k vynásobení výsledné hodnoty ještě koeficientem. Zatím radím nechávat 100 a nepoužívat
