### ISSUE TITLE
chyba při spojení s coinmate api

### ISSUE THREAD

**Issue by seekaaj** [ondra-novak/mmbot#3]
Api spojení s coinmate podúčtem končí chybou: 
`debug [0002][coinmate] RECV: [false,"Api internal error. Error identifier BF.1561532140534.255"]`
S hlavním účtem Api funguje.
Bylo by skvělé, kdyby robot uměl pracovat s podúčty ať nemusí obchodovat přes hlavní účet.

**Comment by ondra-novak** [comment]
Tohle je asi spíš na coinmate.  Mohl bys robota restartovat s parametrem -d a pak zkopírovat část logu přes

$ grep coinmate log/logfile

**Comment by ondra-novak** [comment]
jinak samotná komunikace s coinmate se nikam neloguje (možná promyslet), takže nevěřím, že to nějak pomůže možná snad že identifikujem místo kde to háže tuhle chybu a pošlu to na coinmate na jejich support

**Comment by seekaaj** [comment]
Tak to pravděpodobně byl nějaký interní problém v coinmate. Zkusil jsem vygenerovat nové klíče a spustil robota ve `-vdt` režimu a ten se normálně připojil. Takže to vypadá, že je vyřešeno. 
Jinak za robota moc díky. Těším se na další vývoj.
