### ISSUE TITLE
Wallet details are not shown

### ISSUE THREAD

**Issue by mbexo** [ondra-novak/mmbot#36]
Hi Ondra,

it seems the details in the wallets page are not shown. I have some balance (EUR/BTC) on Bitfinex.

![image](https://user-images.githubusercontent.com/104074935/165066574-3c4523c1-03ed-419f-8eed-a844138418a2.png)

**Comment by mbexo** [comment]
Just an update from my observiation: this happens only when the button "No budget allocation" is turned on. When the button os off, the wallet details are shown in the wallet list.

![image](https://user-images.githubusercontent.com/104074935/174790244-6045da44-dd73-4904-87ec-bf2d6d09d3bb.png)

**Comment by ondra-novak** [comment]
Whole "wallet" feature is built up on wallet allocation. So if you disable this feature, the trader doesn"t rerport any information about wallet and allocations and then the wallet service can"t see it. The main purpose of the feature "no budget allocation" is to help solve allocation clash which can sometime happen if you rebalance your portfolio. This allows to temporarily remove certian trader from allocations and make its balance seen as available.
