### ISSUE TITLE
mmbot.conf

### ISSUE THREAD

**Issue by thorjeus** [ondra-novak/mmbot#4]
Hi,

could you please give a sample of working mmbot.conf ?
i've got error in loading the conf when started.

Thank you.

**Comment by ondra-novak** [comment]
which error you got?

Some example is here
https://github.com/ondra-novak/mmbot/blob/master/conf/traders.conf.ex

If you starting program ensure, that you are in root folder of the project and the command is

$ bin/mmbot start

(bin/ prefix is mandatory for now  - without prefix will unable to find config. this is actally a minor bug I plan to fix in next few  days)

**Comment by thorjeus** [comment]
Hi, thanks for the response.

This is what i've got :
Error: Config option service.inst_file is mandatory but missing.

This could be the config i made is wrong and i'm still trying to make it right.

**Comment by ondra-novak** [comment]
find [service] section and insert below following line
inst_file=../inst

(or some path to non-existing file - file is created as instance file)

**Comment by ondra-novak** [comment]
Version 2.0 is out, this issue is no longer related to current version
