### ISSUE TITLE
Chyba při kompilaci

### ISSUE THREAD

**Issue by seekaaj** [ondra-novak/mmbot#5]
Po update kompilace končí následující chybovkou
```
fatal error: shared/default_app.h: No such file or directory
 #include <shared/default_app.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/main/CMakeFiles/mmbot.dir/build.make:278: recipe for target 'src/main/CMakeFiles/mmbot.dir/main.cpp.o' failed
make[2]: *** [src/main/CMakeFiles/mmbot.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:186: recipe for target 'src/main/CMakeFiles/mmbot.dir/all' failed
make[1]: *** [src/main/CMakeFiles/mmbot.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by valascor** [comment]
I see the same error

Scanning dependencies of target mmbot
[ 58%] Building CXX object src/main/CMakeFiles/mmbot.dir/abstractExtern.cpp.o
/home/john/mmbot/src/main/abstractExtern.cpp:14:23: fatal error: string_view: No such file or directory
compilation terminated.
src/main/CMakeFiles/mmbot.dir/build.make:62: recipe for target 'src/main/CMakeFiles/mmbot.dir/abstractExtern.cpp.o' failed
make[2]: *** [src/main/CMakeFiles/mmbot.dir/abstractExtern.cpp.o] Error 1
CMakeFiles/Makefile2:186: recipe for target 'src/main/CMakeFiles/mmbot.dir/all' failed
make[1]: *** [src/main/CMakeFiles/mmbot.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jack-running** [comment]
mne to konci chybou pri kompilaci poloniex casti:

root@ubuntu:/home/mmbot# make all
[ 35%] Built target simpleServer
[ 57%] Built target imtjson
[ 71%] Built target mmbot
[ 78%] Built target coinmate
[ 79%] Building CXX object src/poloniex/CMakeFiles/poloniex.dir/main.cpp.o
/home/mmbot/src/poloniex/main.cpp: In member function ‘void Interface::syncTrades(std::size_t)’:
/home/mmbot/src/poloniex/main.cpp:301:45: **error**: no matching function for call to ‘min(std::size_t&, long long unsigned int)’
     startTime = std::min(startTime, v.time-1);
                                             ^
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from /home/mmbot/src/poloniex/main.cpp:7:
/usr/include/c++/7/bits/stl_algobase.h:195:5: note: candidate: template<class _Tp> constexpr const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
/home/mmbot/src/poloniex/main.cpp:301:45: note:   deduced conflicting types for parameter ‘const _Tp’ (‘unsigned int’ and ‘long long unsigned int’)
     startTime = std::min(startTime, v.time-1);
                                             ^
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from /home/mmbot/src/poloniex/main.cpp:7:
/usr/include/c++/7/bits/stl_algobase.h:243:5: note: candidate: template<class _Tp, class _Compare> constexpr const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
/home/mmbot/src/poloniex/main.cpp:301:45: note:   deduced conflicting types for parameter ‘const _Tp’ (‘unsigned int’ and ‘long long unsigned int’)
     startTime = std::min(startTime, v.time-1);
                                             ^
In file included from /usr/include/c++/7/functional:64:0,
                 from /home/mmbot/src/imtjson/src/imtjson/rpc.h:18,
                 from /home/mmbot/src/server/src/rpc/rpcServer.h:4,
                 from /home/mmbot/src/poloniex/main.cpp:10:
/usr/include/c++/7/bits/stl_algo.h:3450:5: note: candidate: template<class _Tp> constexpr _Tp std::min(std::initializer_list<_Tp>)
     min(initializer_list<_Tp> __l)
     ^~~
/usr/include/c++/7/bits/stl_algo.h:3450:5: note:   template argument deduction/substitution failed:
/home/mmbot/src/poloniex/main.cpp:301:45: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘unsigned int’
     startTime = std::min(startTime, v.time-1);
                                             ^
In file included from /usr/include/c++/7/functional:64:0,
                 from /home/mmbot/src/imtjson/src/imtjson/rpc.h:18,
                 from /home/mmbot/src/server/src/rpc/rpcServer.h:4,
                 from /home/mmbot/src/poloniex/main.cpp:10:
/usr/include/c++/7/bits/stl_algo.h:3456:5: note: candidate: template<class _Tp, class _Compare> constexpr _Tp std::min(std::initializer_list<_Tp>, _Compare)
     min(initializer_list<_Tp> __l, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algo.h:3456:5: note:   template argument deduction/substitution failed:
/home/mmbot/src/poloniex/main.cpp:301:45: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘unsigned int’
     startTime = std::min(startTime, v.time-1);
                                             ^
src/poloniex/CMakeFiles/poloniex.dir/build.make:62: recipe for target 'src/poloniex/CMakeFiles/poloniex.dir/main.cpp.o' failed
make[2]: *** [src/poloniex/CMakeFiles/poloniex.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:296: recipe for target 'src/poloniex/CMakeFiles/poloniex.dir/all' failed
make[1]: *** [src/poloniex/CMakeFiles/poloniex.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ondra-novak** [comment]
Current commit e28852fa871c620fc163ca9db244d047d9cd2472
+ git submodule update

Succesfully compiled in 
clang++ 6,0,0
g++ 7.4.0
g++ 8.3.0

Reference na <default_app.h> - jedna revize měla špatné reference na submoduly - fixnuto už dřív

Missing string_view - string_view is standard part of C++17 and should be supported by g++ 7 and more

Poslední nahlášena chyba se nepodařilo reprodukovat ale podle výpisu jsem upravil zápis kódu tak, aby to bylo jasnější pro překladač, přičemž ani mě to nehlásí chyby

**Comment by seekaaj** [comment]
Potvrzuji, že po update kompilace proběhla bez problémů. Díky za opravu.
